### ISSUE TITLE
themes.jsonresume.org is down. 

### ISSUE THREAD

**Issue by codeocelot** [jsonresume/theme-manager#25] opened 2015-11-03 21:40 UTC
Related: resume-cli issue 167:  https://github.com/jsonresume/resume-cli/issues/167

Last commit was 6 months ago... so I presume the host environment broke?

**Comment by thomasdavis** [comment] 2015-11-04 00:17
Thanks for the report, checking it out now.

**Comment by PeterDaveHello** [comment] 2015-11-04 06:12
Issue confirmed. @thomasdavis how can I help?

**Comment by dbkaplun** [comment] 2015-11-04 13:28
Looks like it's back up. Closing.

**Closed by dbkaplun** 2015-11-04 13:28 UTC

**Comment by PeterDaveHello** [comment] 2015-11-04 13:31
Any detail about the downtime?

**Comment by thomasdavis** [comment] 2015-11-04 13:35
Was a server crash. It uses pm2 to automatically restart but it just didn't seem to auto restart this time.
